packages:
  - "."

allowBuilds:
  '@google/genai': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false

overrides:
  "@babel/core": 7.29.6
  shell-quote: 1.10.0
  "ws@^7": 7.5.11
  "ws@^8": 8.21.0
