const REVEAL_MS = 1650;
const SWIRL_MS = 720;
const SETTLE_MS = 650;
const FINAL_PASS_OVERLAP_MS = SWIRL_MS * 0.5;

export const SKETCH_CANVAS_INTRO_SLOSH_MS = REVEAL_MS + SWIRL_MS;
export const SKETCH_CANVAS_INTRO_FINAL_PASS_START_MS = (
  SKETCH_CANVAS_INTRO_SLOSH_MS - FINAL_PASS_OVERLAP_MS
);
export const SKETCH_CANVAS_INTRO_TOTAL_MS = Math.max(
  SKETCH_CANVAS_INTRO_SLOSH_MS,
  SKETCH_CANVAS_INTRO_FINAL_PASS_START_MS + SETTLE_MS,
);

export const SKETCH_CANVAS_INTRO = {
  totalMs: SKETCH_CANVAS_INTRO_TOTAL_MS,
  revealMs: REVEAL_MS,
  swirlMs: SWIRL_MS,
  settleMs: SETTLE_MS,
  finalPassStartMs: SKETCH_CANVAS_INTRO_FINAL_PASS_START_MS,
  nodeDelayMs: 20,
  nodeDurationMs: 640,
  connectorDurationMs: 900,
} as const;
